apiVersion: v1
kind: ConfigMap
metadata:
  name: weatherapp-config
  namespace: weatherapp
data:
    ASPNETCORE_ENVIRONMENT: "Staging"
    OpenWeatherMap__BaseUrl: "https://api.openweathermap.org/data/2.5"
    ASPNETCORE_URLS: "http://+:8080"   # tells .NET to listen on all interfaces on 8080
    # CORS — overrides AllowedOrigins array in appsettings.json at runtime.
    # Update AllowedOrigins__2 with the real ingress IP once known.
    AllowedOrigins__0: "http://localhost:5173"
    AllowedOrigins__1: "http://localhost:3000"
    AllowedOrigins__2: "http://20.116.233.3"